# -*- coding: utf-8 -*-
"""TP 1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Iew-y8w3UX0GwyRkmTTHXQjTOdN5tydl

Données historiques (rendements mensuels %, 24 mois)
"""

pip install numpy

import numpy as np

# Portefeuille A (Conservative)
rendements_A = np.array([
1.2, 0.8, -0.5, 1.5, 0.9, 1.1, 0.7, 1.3, 1.0, 0.6, 1.4, 0.8,
1.1, 0.9, -0.3, 1.2, 1.0, 1.5, 0.8, 1.3, 0.9, 1.1, 1.2, 1.0
])
# Portefeuille B (Agressif)
rendements_B = np.array([
4.5, -2.1, 6.2, -3.5, 5.8, 7.1, -1.8, 4.9, 3.2, -4.2, 8.5, -2.7,
5.1, 6.8, -3.1, 7.3, 4.5, -2.9, 6.7, 5.3, -3.8, 7.9, 4.2, 5.5
])

import numpy as np

# Portefeuille A (Conservateur)
rendements_A = np.array([
    1.2, 0.8, -0.5, 1.5, 0.9, 1.1, 0.7, 1.3, 1.0, 0.6, 1.4, 0.8,
    1.1, 0.9, -0.3, 1.2, 1.0, 1.5, 0.8, 1.3, 0.9, 1.1, 1.2, 1.0
]) / 100  # Conversion en proportion

# Portefeuille B (Agressif)
rendements_B = np.array([
    4.5, -2.1, 6.2, -3.5, 5.8, 7.1, -1.8, 4.9, 3.2, -4.2, 8.5, -2.7,
    5.1, 6.8, -3.1, 7.3, 4.5, -2.9, 6.7, 5.3, -3.8, 7.9, 4.2, 5.5
]) / 100  # Conversion en proportion

# Fonction pour calculer et afficher les statistiques
def stats_portefeuille(nom, rendements):
    moyenne_mensuelle = np.mean(rendements) * 100
    ecart_type_mensuel = np.std(rendements, ddof=1) * 100  # écart-type échantillon
    mediane = np.median(rendements) * 100
    rendement_annuel = (np.prod(1 + rendements)**(12/len(rendements)) - 1) * 100
    volatilite_annuelle = np.std(rendements, ddof=1) * np.sqrt(12) * 100

    print(f"{nom}")
    print(f"• Rendement mensuel moyen : {moyenne_mensuelle:.2f}%")
    print(f"• Écart-type mensuel : {ecart_type_mensuel:.2f}%")
    print(f"• Médiane : {mediane:.2f}%")
    print(f"• Rendement annualisé : {rendement_annuel:.2f}%")
    print(f"• Volatilité annualisée : {volatilite_annuelle:.2f}%")
    print("\n")

# Calcul et affichage pour les deux portefeuilles
stats_portefeuille("PORTEFEUILLE A (Conservateur)", rendements_A)
stats_portefeuille("PORTEFEUILLE B (Agressif)", rendements_B)